
version: "3.9"

services:

  nginx:
    build: nginx/
    restart: always
    volumes:
      - ./uwsgi:/tmp/uwsgi/
      - ./staticfiles:/var/www/archiveAPI/assets/:ro
    ports:
      - "3081:80"
    depends_on:
      - django
      - celery

  django:
      build: .
      restart: always
      volumes:
        - ./uwsgi:/tmp/uwsgi/
        - ./staticfiles:/code/staticfiles/
        - /archive:/archive
        - ./:/code

  celery:
    restart: always
    build:
      context: .
    command: celery -A tasks worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - django
    volumes:
      - ./staticfiles:/code/staticfiles/
      - /archive:/archive
      - ./:/code

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks beat -l INFO
    restart: always
    depends_on:
      - celery
      - django

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    restart: always
    env_file:
      - ./.env
    ports:
      - "35672:15672"
      - "3672:5672"
    labels:
      NAME: "rabbitmq1"
#    volumes:
#      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"

  mongodb_container:
    image: mongo:4.4.6
    env_file:
      - ./.env
    ports:
      - 37017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
